package com.archon.model;

public enum Tag {
    ORGANIC, FLESH, BONE, METAL, WOOD, STONE, GLASS, CLAY,
    FLAMMABLE, CONDUCTIVE, BREAKABLE, CONTAINER, VISCOUS, HEAVY, SOLID,
    LIQUID, WATER, OIL, ACID, BLOOD,
    BURNING, WET, FROZEN, CORRODED, PRONE, STUNNED, BLIND, LIT, EXTINGUISHER
}